#soubor: Makefile
# Michal Ruprich, xrupri00, RedHat, SSDS - hawkey example

CC=g++
CFLAGS=-O2 -g -Wall -Wextra -pedantic  -std=c++11 -fPIC
INCLUDE=/usr/include/hawkey
all: hawkey_ex

readerWriter: havkey_ex.cpp
	$(CC) $(CFLAGS) -I$(INCLUDE) -o hawkey_ex hawkey_ex.cpp
